/// <reference types="cypress" />



//This is a test suite
describe('Regression test suite',function(){

    //This is a test case
    it('Perform valid login',function(){
       cy.visit('http://localhost:3000/login') 
       cy.title().should('include','Hotel')
       cy.contains('Login')
       cy.get(':nth-child(1) > input').type('tester01')
       cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
       cy.get('.btn').click()
       cy.contains('Tester Hotel Overview')
       cy.get('.user > .btn').click()
       cy.contains('Login')

    })
    it('Create new Client',function(){
        cy.visit('http://localhost:3000/login') 
        cy.title().should('include','Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.blocks > :nth-child(2) > .btn').click()
        cy.contains('Clients')
        cy.get('h2 > .btn').click()
        cy.get(':nth-child(1) > input').type('Kalle Anka')
        cy.get(':nth-child(2) > input').type('kalle.anka@anka.com')
        cy.get(':nth-child(3) > input').type('0701234567')
        cy.get('.blue').click()
        cy.contains('Clients')
        cy.get('.user > .btn').click()
        cy.contains('Login')
 
     })
     it('Edit Client',function(){
        cy.visit('http://localhost:3000/login') 
        cy.title().should('include','Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.blocks > :nth-child(2) > .btn').click()
        cy.contains('Clients')
        cy.get('h2 > .btn').click()
        cy.get(':nth-child(1) > input').type('Kalle Anka')
        cy.get(':nth-child(2) > input').type('kalle.anka@anka.com')
        cy.get(':nth-child(3) > input').type('0701234567')
        cy.get('.blue').click()
        cy.contains('Clients')
        cy.get(':nth-child(3) > .action > img').click()
        cy.get('.menu > :nth-child(1)').click()
        cy.contains('Client:')
        cy.get(':nth-child(3) > input').type('Edit')
        cy.get(':nth-child(4) > input').type('Edit')
        cy.get(':nth-child(5) > input').type('99')
        cy.get('.blue').click()
        cy.contains('Clients')
        cy.get('.user > .btn').click()
        cy.contains('Login')
 
     })

    it('Delete Client',function(){
        cy.visit('http://localhost:3000/login') 
        cy.title().should('include','Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.blocks > :nth-child(2) > .btn').click()
        cy.contains('Clients')
        cy.get('h2 > .btn').click()
        cy.get(':nth-child(1) > input').type('Kalle Anka')
        cy.get(':nth-child(2) > input').type('kalle.anka@anka.com')
        cy.get(':nth-child(3) > input').type('0701234567')
        cy.get('.blue').click()
        cy.contains('Clients')
        cy.get(':nth-child(3) > .action > img').click()
        cy.get('.menu > :nth-child(2)').click()
        cy.contains('Clients')
        cy.get('.user > .btn').click()
        cy.contains('Login')

     })

    it('Create new Room',function(){
        cy.visit('http://localhost:3000/login') 
        cy.title().should('include','Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.blocks > :nth-child(1) > .btn').click()
        cy.contains('Rooms')
        cy.get('h2 > .btn').click()
        cy.get(':nth-child(1) > select').select('Double')
        cy.get(':nth-child(2) > input').type('45')
        cy.get(':nth-child(3) > input').type('4')
        cy.get(':nth-child(5) > input').type('444')        
        cy.get('.blue').click()
        cy.get('.user > .btn').click()
        cy.contains('Login')
 
     })
     it.only('Create new Bill',function(){
        cy.visit('http://localhost:3000/login') 
        cy.title().should('include','Hotel')
        cy.contains('Login')
        cy.get(':nth-child(1) > input').type('tester01')
        cy.get(':nth-child(2) > input').type('GteteqbQQgSr88SwNExUQv2ydb7xuf8c')
        cy.get('.btn').click()
        cy.contains('Tester Hotel Overview')
        cy.get('.blocks > :nth-child(3) > .btn').click()
        cy.contains('Bills')
        cy.get('h2 > .btn').click()
        cy.get(':nth-child(1) > input').type('45')
        cy.get('.checkbox').click()    
        cy.get('.blue').click()
        cy.get('.user > .btn').click()
        cy.contains('Login')
 
     })
})